[MIG] account_periodical_invoicing: migration scripts
serviciosbaeza/serviciosbaeza-odoo-addons pull request #36
Opened 2017-12-20 12:42 UTC by cubells

Migration scripts of module account_periodical_invoicing which is merged into contract.

cc @Tecnativa

2017-12-20 15:58 UTC, pedrobaeza requested changes
Al final tienes que marcar el módulo contract como `to upgrade` para que se haga el resto del proceso.

2017-12-20 15:58 UTC, pedrobaeza commented on account_periodical_invoicing/migrations/9.0.1.1.0/pre-migration.py
> +_column_renames = {
Utiliza `rename_fields` en lugar de `rename_columns` para aprovechar las ventajas que tiene.

2017-12-20 15:58 UTC, pedrobaeza commented on account_periodical_invoicing/migrations/9.0.1.1.0/pre-migration.py
> +    ('account_periodical_invoicing_agreement',
Esto no se puede hacer, porque la otra tabla ya existe. Tendrás que copiar datos...

2017-12-20 15:58 UTC, pedrobaeza commented on account_periodical_invoicing/migrations/9.0.1.1.0/pre-migration.py
> +    ('account_periodical_invoicing_agreement_line',
Esto está repetido

2017-12-20 15:58 UTC, pedrobaeza commented on account_periodical_invoicing/migrations/9.0.1.1.0/pre-migration.py
> +    openupgrade.rename_tables(env.cr, _table_renames)
Llama también a `rename_models` donde se pueda.

2017-12-20 15:58 UTC, pedrobaeza commented on account_periodical_invoicing/migrations/9.0.1.1.0/pre-migration.py
> +    'account_analytic_account': [
Estas columnas vas a tener que añadirlas a mano, ya que no se puede renombrar la tabla porque ya existe.

2017-12-20 15:58 UTC, pedrobaeza commented on account_periodical_invoicing/migrations/9.0.1.1.0/pre-migration.py
> +    openupgrade.logged_query(env.cr, """
Haz las dos cosas en una sola consulta `UPDATE`

2017-12-20 16:23 UTC, cubells commented on account_periodical_invoicing/migrations/9.0.1.1.0/pre-migration.py
> +_column_renames = {
No debería de hacer un copy_columns del campo de res_partner para preservar datos y el resto rename_fields?

2017-12-20 16:49 UTC, pedrobaeza commented on account_periodical_invoicing/migrations/9.0.1.1.0/pre-migration.py
> +_column_renames = {
Vale, de los que hay map_values, sí

2017-12-20 17:11 UTC, cubells commented
@pedrobaeza puedes revisar otra vez?

2017-12-20 17:17 UTC, pedrobaeza commented on account_periodical_invoicing/migrations/9.0.1.1.0/pre-migration.py
> +    ('account_periodical_invoicing_agreement',
Pero con esta tabla sigues sin poder hacer esto: ni renombrar modelo ni renombrar tabla, porque como digo, ya existe.

2017-12-20 17:18 UTC, pedrobaeza commented on account_periodical_invoicing/migrations/9.0.1.1.0/pre-migration.py
> +    ('account_periodical_invoicing_agreement_line',
Hay que renombrar la tabla además del modelo.

2017-12-20 17:18 UTC, pedrobaeza commented on account_periodical_invoicing/migrations/9.0.1.1.0/pre-migration.py
> +_column_renames = {
Pero lo que has hecho no es copiarla, si no renombrarla...

2017-12-20 17:18 UTC, pedrobaeza commented
El post-migration tienes que eliminarlo. Eso era de la versión 8

2017-12-20 17:19 UTC, pedrobaeza commented on account_periodical_invoicing/migrations/9.0.1.1.0/pre-migration.py
> +        SET name = q.product_name, uom_id = q.uom_id
No necesitas una subquery. Se puede hacer todo en una misma consulta `UPDATE`

2017-12-21 00:06 UTC, pedrobaeza requested changes
Sigue faltando la copia de los elementos de account_periodical_invoicing_agreement a account_analytic_account, y claro, luego hay que reasignar los IDs de las líneas a los nuevos de la tabla account_analytic_account

2017-12-21 08:14 UTC, cubells commented
@pedrobaeza 
dos dudas:
Se debería de hacer la copia de datos en el post, verdad?
No tengo claro cómo reasignar los ids de las lineas a los nuevos contratos. Alguna idea o ejemplo?

2017-12-21 08:20 UTC, pedrobaeza commented
Sí sería en el post. Ya lo termino yo, venga.

2017-12-21 11:25 UTC, cubells commented
Me parece perfecta la solución.

Has comprobado que active = True en account.periodical_invoicing.agreement?

Si no se darán de alta contratos que estaban caducados no?

2017-12-21 11:27 UTC, pedrobaeza commented
Uhm, hay dos cosas que ahora mismo no están contempladas además de eso que comentas:

- end_date si aplica
- intervalos diferentes en las líneas.

Voy a echar un vistazo a eso.

2017-12-21 11:29 UTC, cubells commented
Si, no es fácil la migración. Si recuerdo más cosas de mi análisis te digo.

2017-12-21 17:45 UTC, pedrobaeza commented
Bueno, ahora parece haber quedado correcto. Luego le echas un vistazo si quieres.

2017-12-21 17:45 UTC, merged